export const serviceCategories = [
  {
    id: 'fire-engineering',
    title: 'Fire Engineering Services',
    icon: '🔥',
    services: [
      'Fire Risk Assessment',
      'Fire Safety Audits',
      'Fire Protection System Evaluation',
      'Fire Detection & Alarm Assessment',
      'Fire Hydrant & Sprinkler Assessment',
      'Emergency Response Planning',
      'Fire Mock Drills',
      'Fire Incident Investigation',
      'Fire Warden & Marshal Training',
      'Fire Safety Compliance Advisory',
    ],
  },
  {
    id: 'industrial-safety',
    title: 'Industrial Safety Services',
    icon: '🏭',
    services: [
      'Safety Audits',
      'Risk Assessment',
      'JSA/JHA',
      'Machine Safety',
      'Electrical Safety',
      'LOTO/HIRA',
      'Permit to Work',
      'Contractor Safety',
      'Scaffolding Safety',
      'Behaviour Based Safety',
      'CMC - Contractor Management Centre',
    ],
  },
  {
    id: 'occupational-health',
    title: 'Occupational Health & Environment',
    icon: '🏥',
    services: [
      'Industrial Hygiene',
      'Noise & Heat Stress Assessment',
      'Indoor Air Quality',
      'Chemical Exposure',
      'Ergonomics',
      'PPE Assessment',
      'Environmental Compliance',
      'Waste Management',
    ],
  },
  {
    id: 'hse-consultancy',
    title: 'HSE Consultancy & Compliance',
    icon: '📋',
    services: [
      'Factory Act Compliance',
      'Construction Safety Compliance',
      'ISO 45001 Support',
      'ISO 14001 Support',
      'Compliance Gap Assessment',
      'HSE Management Systems',
    ],
  },
  {
    id: 'safety-audits',
    title: 'Safety Audits & Inspections',
    icon: '🔍',
    services: [
      'Comprehensive Safety Audits',
      'Fire Safety Audits',
      'Electrical Safety Audits',
      'Construction Safety Audits',
      'Behavioural Safety Audits',
      'Corrective Action Monitoring',
    ],
  },
  {
    id: 'emergency-preparedness',
    title: 'Emergency Preparedness',
    icon: '🚨',
    services: [
      'Emergency Exit Plans',
      'Disaster Management',
      'Mock Drills',
      'ERT Training',
      'Business Continuity Planning',
      'Site Evacuation',
    ],
  },
  {
    id: 'trainings',
    title: 'Trainings',
    icon: '📚',
    services: [
      'Safety Induction',
      'Work at Height',
      'Confined Space',
      'Scaffolding',
      'Electrical Safety',
      'Major Fire Safety',
      'Leadership Programs',
      'DDT – Defensive Driving Training',
      'BBS - Behaviour Based Safety',
      'Basic First Aid Training',
    ],
  },
  {
    id: 'manpower-deployment',
    title: 'Manpower Deployment',
    icon: '👷',
    services: [
      'Safety Officers',
      'Safety Supervisors',
      'HSE Engineers',
      'Fire Officers',
      'Fire Marshals',
      'DCPO',
      'Firemen',
      'Project HSE Teams',
      'CMC Executives',
      'DMC Executives',
    ],
  },
  {
    id: 'ai-digital-safety',
    title: 'AI-Enabled Digital Safety',
    icon: '🤖',
    services: [
      'AI Vision Monitoring',
      'PPE Detection',
      'Unsafe Act Detection',
      'Digital PTW',
      'Incident Management',
      'Safety Dashboards',
      'Predictive Analytics',
      'Safety Software Solutions',
    ],
  },
  {
    id: 'technical-education',
    title: 'Technical Education',
    icon: '🎓',
    services: [
      'Diploma Programs',
      'Advanced Diploma',
      'Certificate Courses',
      'Industrial Internship',
      'Placement Assistance',
      'Executive Development',
      'All Govt University / NSDC Programs',
    ],
  },
];

export const approach = {
  title: 'Our Approach',
  steps: ['Assessment', 'Planning', 'Implementation', 'Monitoring', 'Continuous Improvement'],
};

export const whyChooseUs = [
  'Engineering Expertise',
  'Industry Experience',
  'Integrated HSE Services',
  'AI-Enabled Safety Solutions',
  'Pan-India Network',
  'Quality & Integrity',
];

export const qualityPolicy = [
  'Deliver quality education aligned with evolving industry needs.',
  'Develop competent professionals through practical, skill-based learning.',
  'Promote excellence in fire engineering, industrial safety, occupational health & safety, and corporate HSE services.',
  'Support industries with reliable, innovative, and value-driven safety solutions.',
  'Achieve high levels of student success, employability, and employer satisfaction.',
  'Foster a culture of continuous improvement, innovation, and professional excellence.',
  'Comply with applicable statutory, regulatory, national, and internationally accepted standards.',
  'Continuously enhance our people, processes, infrastructure, and management systems to exceed stakeholder expectations.',
];
